# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development

In [4]:
#pip install nbconvert pip install pyppeteer

In [2]:
#--allow-chromium-download

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [5]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [7]:
#Code comes here

ones_array = np.ones(10)
print(ones_array)

integers_array = np.arange(1, 21)
print(ones_array)

matrix_array = np.ones((1,5,5), dtype="int")
print(matrix_array)
print(matrix_array.dtype)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
int64


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [9]:
# Code comes here

matrix_3d = np.random.randn(3, 3, 3)
print(matrix_3d)

array_1d = matrix_3d.reshape(27)
print(array_1d)

[[[-0.83402991  0.91627687  0.3353395 ]
  [ 0.6744778   0.82175196 -0.26346026]
  [ 0.07874084  0.15876063 -1.55920113]]

 [[ 1.40179103 -1.31032094  0.57482221]
  [-0.06139339  1.65288932  0.94966123]
  [-1.07332913 -0.30954147 -0.51433162]]

 [[-0.13282349 -0.84731627  1.53142949]
  [ 1.07619243 -1.0031597   0.92008042]
  [ 1.53441706  0.24554827  0.81779749]]]
[-0.83402991  0.91627687  0.3353395   0.6744778   0.82175196 -0.26346026
  0.07874084  0.15876063 -1.55920113  1.40179103 -1.31032094  0.57482221
 -0.06139339  1.65288932  0.94966123 -1.07332913 -0.30954147 -0.51433162
 -0.13282349 -0.84731627  1.53142949  1.07619243 -1.0031597   0.92008042
  1.53441706  0.24554827  0.81779749]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [11]:
# Code comes here

arr20 = np.linspace(1, 10, 20)
print(arr20)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [22]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [13]:
20

20

In [24]:
import numpy as np
a = np.arange(1, 26).reshape(5, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
reshapearray = a[1:5, 3:5]
print(reshapearray)

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [26]:
# Code come here
reshapearrary_2 = a[1,0:5]
print(reshapearrary_2)

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [27]:
# Code comes here

total_sum = a.sum()
print(total_sum)

325


## 2.6 

Calculate the sum of each row in `a`.

In [29]:
# Code comes here

row_sum = a.sum(axis=1)
print(row_sum)

[ 15  40  65  90 115]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [30]:
# Code comes here
a = np.arange(1, 26).reshape(5, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [33]:
mean_a = a.mean()
print("\nMean of the array")
print(mean_a)


Mean of the array
13.0


In [37]:
booleanmask = a > mean_a
print(booleanmask)

[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [39]:
above_mean = a[booleanmask]
print("\Values greater than the mean:")
print(above_mean)

\Values greater than the mean:
[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [40]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [43]:
# Code comes here

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"

carbonfootprint_df = pd.read_csv(url)

carbonfootprint_df.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [44]:
#Code comes here
print(len(carbonfootprint_df))

1430


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [49]:
# Code comes here

mean_co2 = carbonfootprint_df["co2_emmission"].mean()
print(mean_co2)

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [60]:
# Code comes here

max_co2 = carbonfootprint_df["co2_emmission"].max()
print(max_co2)

1712.0


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [62]:
#code comes here
high_co2 = carbonfootprint_df[carbonfootprint_df["co2_emmission"] > 1000]
print(high_co2)

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94


In [64]:
num_countries = high_co2["country"].nunique()
print(num_countries)

5


## 2.14

Which country consumes the least amount of beef per person per year?


In [73]:
# code comes here

#first I need to select only the rows for beef:
beef_df = carbonfootprint_df[carbonfootprint_df["food_category"] == "Beef"]

#now I need to find the lowest consumption:
lowest_beef = beef_df["consumption"].min()

#now I can find the country with the lowest beef consumption. 
country_min_beef = beef_df[beef_df["consumption"] == lowest_beef]["country"]

#now I can print the result
print(country_min_beef.tolist())

['Liberia']


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [78]:
# code comes here

#first I need to create a line to define what meat products are:
meat_products = ["Beef", "Pork", "Fish", "Poultry", "Lamb & Goat"]

#now I can filter the dataset for meat products. I do this by creating a boolean mask for rows where the food is one of the meat products.
meat_df = carbonfootprint_df[carbonfootprint_df["food_category"].isin(meat_products)]

# Now I can sum the CO2 emissions
total_meat_emissions = meat_df["co2_emmission"].sum()

#finally, I need to print the result.
print(total_meat_emissions)

74441.13


# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [86]:
# code comes here

#First, I filter to find everything that is not in the meat_products list from before using the symbol ~
non_meat_df = carbonfootprint_df[~carbonfootprint_df["food_category"].isin(meat_products)]

#Now you sum the CO2 emissions of all other food products
total_non_meat_emissions = non_meat_df["co2_emmission"].sum()

#finally, you print the result
print(total_non_meat_emissions)

31927.98


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.